name: Build Project

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm ci
        run: |
          make install
      - name: Run airbnb eslint
        run: 
          make lint
