name: eslint

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run airbnb eslint
      run:
        make lint  
